services:
  binance-monitor:
    build: .
    container_name: node-monitor
    ports:
      - "3333:3333"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3333
